SELECT * FROM customer limit 20;

SELECT column_name
FROM information_schema.columns
WHERE table_name = 'customer';

--Q1. What is the total revenue generated by male vs. female customers?
SELECT gender, SUM ("purchase_amount_(usd)") as revenue
FROM customer 
GROUP BY gender;


--Q2. Which customers used a discount but still spent more than the average purchase amount?

select customer_id, ("purchase_amount_(usd)")
from customer 
where discount_applied = 'Yes' and ("purchase_amount_(usd)" >= (select AVG("purchase_amount_(usd)") from customer)

--Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, ROUND(AVG(review_rating::numeric),2) as "average product rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;


--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.

select shipping_type,
ROUND(AVG("purchase_amount_(usd)"),2) AS avg_purchase
from customer 
where shipping_type in ('standard','express')
group by shipping_type



--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

select subscription_status,
COUNT(customer_id) as total_customers,
ROUND(AVG("purchase_amount_(usd)"),2) as avg_spend,
ROUND(SUM("purchase_amount_(usd)"),2) as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spend desc;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT item_purchased,
       ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;


--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases.

with customer_type as (
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM customer)

select customer_segment,count(*) AS "Number of Customers" 
from customer_type 
group by customer_segment;

--Q8. What are the top 3 most purchased products within each category?

WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

--Q10. What is the revenue contribution of each age group?

SELECT 
  CASE 
     WHEN age < 20 THEN 'under 20'
	 WHEN age BETWEEN 20 AND 29
THEN '20-29'
     WHEN age BETWEEN 30 AND 39 
THEN '30-39'
     WHEN age BETWEEN 40 AND 49 
THEN '40-49'
    ELSE '50+'
	END AS age_group,
    SUM("purchase_amount_(usd)") AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue desc;